<h2>Adicionando Usuário</h2>

<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('class', 'stdform');
$form->setAttribute('role', 'form');
echo $this->form()->openTag($form);
?>

<!-------------------------------------------------------------->
<p>
    <?php $erros = $form->get('role_id')->getMessages(); ?>
    <?php $numErros = count($erros); ?>

<div class="par control-group bloco <?php if ($numErros > 0): ?>error<?php endif; ?>">
    <div class="controls">
        <?php
        $element = $this->elementSelect->setName('role_id');
        $selectValues = array();
        if ( $roles ) {
            foreach($roles as $role) {
                $selectValues[$role->getId()] = $role->getName();
            }
        }

        $element->setValueOptions($selectValues);

        echo $this->formLabel($form->get('role_id'));
        echo $this->formSelect($element);
        ?>

        <?php if ($numErros > 0): ?>
            <?php foreach ($erros as $chave => $msg): ?>
                <small class="desc-erro help-inline"><?php echo $msg; ?></small>
            <?php endforeach; ?>
        <?php endif; ?>

    </div>
</div>
</p>
<!-------------------------------------------------------------->

<!-------------------------------------------------------------->
<p>
<?php $erros = $form->get('name')->getMessages(); ?>
<?php $numErros = count($erros); ?>

<div class="par control-group bloco <?php if ($numErros > 0): ?>error<?php endif; ?>">
    <?php echo $this->formLabel($form->get('name')) ?>
    <div class="controls">
        <?php echo $this->formInput($form->get('name')) ?>

        <?php if ($numErros > 0): ?>
            <?php foreach ($erros as $chave => $msg): ?>
                <small class="desc-erro help-inline"><?php echo $msg; ?></small>
            <?php endforeach; ?>
        <?php endif; ?>

    </div>
</div>
</p>
<!-------------------------------------------------------------->

<!-------------------------------------------------------------->
<p>
<?php $erros = $form->get('email')->getMessages(); ?>
<?php $numErros = count($erros); ?>

<div class="par control-group bloco <?php if ($numErros > 0): ?>error<?php endif; ?>">
    <?php echo $this->formLabel($form->get('email')); ?>
    <div class="controls">
        <?php echo $this->formEmail($form->get('email')); ?>

        <?php if ($numErros > 0): ?>
            <?php foreach ($erros as $chave => $msg): ?>
                <small class="desc-erro help-inline"><?php echo $msg; ?></small>
            <?php endforeach; ?>
        <?php endif; ?>

    </div>
</div>
</p>
<!-------------------------------------------------------------->

<!-------------------------------------------------------------->
<p>
<?php $erros = $form->get('password')->getMessages(); ?>
<?php $numErros = count($erros); ?>

<div class="par control-group bloco <?php if ($numErros > 0): ?>error<?php endif; ?>">
    <?php echo $this->formLabel($form->get('password')); ?>
    <div class="controls">
        <?php echo $this->formPassword($form->get('password')); ?>

        <?php if ($numErros > 0): ?>
            <?php foreach ($erros as $chave => $msg): ?>
                <small class="desc-erro help-inline"><?php echo $msg; ?></small>
            <?php endforeach; ?>
        <?php endif; ?>

    </div>
</div>
</p>
<!-------------------------------------------------------------->

<!-------------------------------------------------------------->
<p>
<?php $erros = $form->get('password_confirm')->getMessages(); ?>
<?php $numErros = count($erros); ?>

<div class="par control-group bloco <?php if ($numErros > 0): ?>error<?php endif; ?>">
    <?php echo $this->formLabel($form->get('password_confirm')); ?>
    <div class="controls">
        <?php echo $this->formPassword($form->get('password_confirm')); ?>

        <?php if ($numErros > 0): ?>
            <?php foreach ($erros as $chave => $msg): ?>
                <small class="desc-erro help-inline"><?php echo $msg; ?></small>
            <?php endforeach; ?>
        <?php endif; ?>

    </div>
</div>
</p>
<!-------------------------------------------------------------->

<p class="stdformbutton">
    <?php echo $this->formButton($form->get('submit')); ?>
</p>

<?php echo $this->form()->closeTag(); ?>