<article class="conteudo clearfix">
    <div class="row">

        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
            <h2>Cadastro</h2>
            <p>Informe seus dados e faça parte de nossa rede</p>
            <br/>
            <div class="row">
                <?php
                    $form = $this->form;
                    $form->prepare();

                    echo $this->form()->openTag($form);
                ?>

                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                    <?php $erros = $form->get('name')->getMessages(); ?> 
                    <?php $numErros = count($erros); ?>
                    <div class="form-group <?php if ($numErros > 0) echo 'has-error has-feedback'; ?>">

                        <div class="par control-group bloco <?php if ($numErros > 0): ?>error<?php endif; ?>">
                            <?php echo $this->formLabel($form->get('name')) ?>
                            <div class="controls">
                                <?php echo $this->formInput($form->get('name')) ?>

                                <?php if ($numErros > 0): ?>
                                    <?php foreach ($erros as $chave => $msg): ?>
                                        <small class="desc-erro help-inline"><?php echo $msg; ?></small>
                                    <?php endforeach; ?>
                                <?php endif; ?>  

                            </div>
                        </div>  
                    </div>
                </div>
                
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">

                    <?php $erros = $form->get('email')->getMessages(); ?> 
                    <?php $numErros = count($erros); ?>
                    <div class="form-group <?php if ($numErros > 0) echo 'has-error has-feedback'; ?>">
                        <div class="par control-group bloco <?php if ($numErros > 0): ?>error<?php endif; ?>">
                            <?php echo $this->formLabel($form->get('email')) ?>
                            <div class="controls">
                                <?php echo $this->formInput($form->get('email')) ?>

                                <?php if ($numErros > 0): ?>
                                    <?php foreach ($erros as $chave => $msg): ?>
                                        <small class="desc-erro help-inline"><?php echo $msg; ?></small>
                                        <?php if ($numErros > 1) echo '<br />'; ?>
                                    <?php endforeach; ?>
                                <?php endif; ?>  

                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                    <?php $erros = $form->get('password')->getMessages(); ?> 
                    <?php $numErros = count($erros); ?>
                    <div class="form-group <?php if ($numErros > 0) echo 'has-error has-feedback'; ?>">
                        <div class="par control-group bloco <?php if ($numErros > 0): ?>error<?php endif; ?>">
                            <?php echo $this->formLabel($form->get('password')) ?>
                            <div class="controls">
                                <?php echo $this->formInput($form->get('password')) ?>

                                <?php if ($numErros > 0): ?>
                                    <?php foreach ($erros as $chave => $msg): ?>
                                        <small class="desc-erro help-inline"><?php echo $msg; ?></small>
                                        <?php if ($numErros > 1) echo '<br />'; ?>
                                    <?php endforeach; ?>
                                <?php endif; ?>  

                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                    <?php $erros = $form->get('password_confirm')->getMessages(); ?> 
                    <?php $numErros = count($erros); ?>
                    <div class="form-group <?php if ($numErros > 0) echo 'has-error has-feedback'; ?>">
                        <div class="par control-group bloco <?php if ($numErros > 0): ?>error<?php endif; ?>">
                            <?php echo $this->formLabel($form->get('password_confirm')) ?>
                            <div class="controls">
                                <?php echo $this->formInput($form->get('password_confirm')) ?>

                                <?php if ($numErros > 0): ?>
                                    <?php foreach ($erros as $chave => $msg): ?>
                                        <small class="desc-erro help-inline"><?php echo $msg; ?></small>
                                    <?php endforeach; ?>
                                <?php endif; ?>  

                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                    <?php $erros = $form->get('phone')->getMessages(); ?> 
                    <?php $numErros = count($erros); ?>
                    <div class="form-group <?php if ($numErros > 0) echo 'has-error has-feedback'; ?>">
                        <div class="par control-group bloco <?php if ($numErros > 0): ?>error<?php endif; ?>">
                            <?php echo $this->formLabel($form->get('phone')) ?>
                            <div class="controls">
                                <?php echo $this->formInput($form->get('phone')) ?>

                                <?php if ($numErros > 0): ?>
                                    <?php foreach ($erros as $chave => $msg): ?>
                                        <small class="desc-erro help-inline"><?php echo $msg; ?></small>
                                    <?php endforeach; ?>
                                <?php endif; ?>  

                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                    <?php $erros = $form->get('cpf')->getMessages(); ?> 
                    <?php $numErros = count($erros); ?>
                    <div class="form-group <?php if ($numErros > 0) echo 'has-error has-feedback'; ?>">
                        <div class="par control-group bloco <?php if ($numErros > 0): ?>error<?php endif; ?>">
                            <?php echo $this->formLabel($form->get('cpf')) ?>
                            <div class="controls">
                                <?php echo $this->formInput($form->get('cpf')) ?>

                                <?php if ($numErros > 0): ?>
                                    <?php foreach ($erros as $chave => $msg): ?>
                                        <small class="desc-erro help-inline"><?php echo $msg; ?></small>
                                    <?php endforeach; ?>
                                <?php endif; ?>  

                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="clearfix"></div>

                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <?php $erros = $form->get('address')->getMessages(); ?> 
                    <?php $numErros = count($erros); ?>
                    <div class="form-group <?php if ($numErros > 0) echo 'has-error has-feedback'; ?>">
                        <div class="par control-group bloco <?php if ($numErros > 0): ?>error<?php endif; ?>">
                            <?php echo $this->formLabel($form->get('address')) ?>
                            <div class="controls">
                                <?php echo $this->formInput($form->get('address')) ?>

                                <?php if ($numErros > 0): ?>
                                    <?php foreach ($erros as $chave => $msg): ?>
                                        <small class="desc-erro help-inline"><?php echo $msg; ?></small>
                                    <?php endforeach; ?>
                                <?php endif; ?>  

                            </div>
                        </div>
                    </div>
                </div>

                <div class="clearfix"></div>
                
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                    <?php $erros = $form->get('address_number')->getMessages(); ?> 
                    <?php $numErros = count($erros); ?>
                    <div class="form-group <?php if ($numErros > 0) echo 'has-error has-feedback'; ?>">
                        <div class="par control-group bloco <?php if ($numErros > 0): ?>error<?php endif; ?>">
                            <?php echo $this->formLabel($form->get('address_number')) ?>
                            <div class="controls">
                                <?php echo $this->formInput($form->get('address_number')) ?>

                                <?php if ($numErros > 0): ?>
                                    <?php foreach ($erros as $chave => $msg): ?>
                                        <small class="desc-erro help-inline"><?php echo $msg; ?></small>
                                    <?php endforeach; ?>
                                <?php endif; ?>  

                            </div>
                        </div>
                    </div>
                </div>  

                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                    <div class="form-group">
                        <div class="par control-group bloco">
                            <?php echo $this->formLabel($form->get('address_complement')) ?>
                            <div class="controls">
                                <?php echo $this->formInput($form->get('address_complement')) ?>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                    <?php $erros = $form->get('district')->getMessages(); ?> 
                    <?php $numErros = count($erros); ?>
                    <div class="form-group <?php if ($numErros > 0) echo 'has-error has-feedback'; ?>">
                        <div class="par control-group bloco <?php if ($numErros > 0): ?>error<?php endif; ?>">
                            <?php echo $this->formLabel($form->get('district')) ?>
                            <div class="controls">
                                <?php echo $this->formInput($form->get('district')) ?>

                                <?php if ($numErros > 0): ?>
                                    <?php foreach ($erros as $chave => $msg): ?>
                                        <small class="desc-erro help-inline"><?php echo $msg; ?></small>
                                    <?php endforeach; ?>
                                <?php endif; ?>  

                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                    <?php $erros = $form->get('city')->getMessages(); ?> 
                    <?php $numErros = count($erros); ?>
                    <div class="form-group <?php if ($numErros > 0) echo 'has-error has-feedback'; ?>">
                        <div class="par control-group bloco <?php if ($numErros > 0): ?>error<?php endif; ?>">
                            <?php echo $this->formLabel($form->get('city')) ?>
                            <div class="controls">
                                <?php echo $this->formInput($form->get('city')) ?>

                                <?php if ($numErros > 0): ?>
                                    <?php foreach ($erros as $chave => $msg): ?>
                                        <small class="desc-erro help-inline"><?php echo $msg; ?></small>
                                    <?php endforeach; ?>
                                <?php endif; ?>  

                            </div>
                        </div>
                    </div>
                </div>

                <div class="clearfix"></div>

                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                    <?php $erros = $form->get('state')->getMessages(); ?> 
                    <?php $numErros = count($erros); ?>
                    <div class="form-group <?php if ($numErros > 0) echo 'has-error has-feedback'; ?>">
                        <div class="par control-group bloco <?php if ($numErros > 0): ?>error<?php endif; ?>">
                            <?php echo $this->formLabel($form->get('state')) ?>
                            <div class="controls">
                                <?php echo $this->formSelect($form->get('state')) ?>

                                <?php if ($numErros > 0): ?>
                                    <?php foreach ($erros as $chave => $msg): ?>
                                        <small class="desc-erro help-inline"><?php echo $msg; ?></small>
                                    <?php endforeach; ?>
                                <?php endif; ?>  

                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                    <?php $erros = $form->get('cep')->getMessages(); ?> 
                    <?php $numErros = count($erros); ?>
                    <div class="form-group <?php if ($numErros > 0) echo 'has-error has-feedback'; ?>">
                        <div class="par control-group bloco <?php if ($numErros > 0): ?>error<?php endif; ?>">
                            <?php echo $this->formLabel($form->get('cep')) ?>
                            <div class="controls">
                                <div class="cep-com-busca">
                                    <?php echo $this->formInput($form->get('cep')) ?>
                                    <?php echo $this->partial('partials/busca-cep', array('message' => '&nbsp;', 'classForElement' => 'glyphicon glyphicon-search busca-cep')); ?>
                                </div>
                                
                                <?php if ($numErros > 0): ?>
                                    <?php foreach ($erros as $chave => $msg): ?>
                                        <small class="desc-erro help-inline"><?php echo $msg; ?></small>
                                    <?php endforeach; ?>
                                <?php endif; ?>       
                            </div>
                        </div>
                    </div>
                </div>

                <div class="clearfix"></div>

                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="form-group">
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                    </div>
                </div>

                <?php echo $this->form()->closeTag(); ?>

            </div>
        </div> 

    </div>
</article>